services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./docker-data/mongo:/data/db
    environment:
      MONGO_INITDB_DATABASE: topic_cluster
